### ISSUE TITLE
dagger.hilt.android.components.ApplicationComponent is not a valid Component. Did you add or remove code in package hilt_aggregated_deps?

### ISSUE THREAD

**Issue by b95505017** [google/dagger#1987]
It seems that Hilt `2.28.2` does not compatible with `androidx.hilt`. Maybe caused by newly introduced `SingletonComponent`?

```
error: [Hilt]
  dagger.hilt.android.components.ApplicationComponent is not a valid Component. Did you add or remove code in package hilt_aggregated_deps? [dagger.hilt.android.components.ApplicationComponent]: java.lang.IllegalStateException: dagger.hilt.android.components.ApplicationComponent is not a valid Component. Did you add or remove code in package hilt_aggregated_deps? [dagger.hilt.android.components.ApplicationComponent]
  	at com.google.common.base.Preconditions.checkState(Preconditions.java:843)
  	at dagger.hilt.processor.internal.aggregateddeps.ComponentDependencies.from(ComponentDependencies.java:197)
  	at dagger.hilt.processor.internal.root.RootProcessor.postRoundProcess(RootProcessor.java:139)
  	at dagger.hilt.processor.internal.BaseProcessor.process(BaseProcessor.java:190)
```

**Comment by danysantiago** [comment]
Yup - There should be a release of `androidx.hilt` soon to address this. Sorry for the inconvenience.

**Comment by SteinerOkay** [comment]
@danysantiago did you miss release version **2.28.3-alpha** of Gradle plugin [https://search.maven.org/search?q=a:hilt-android-gradle-plugin](url)?

**Comment by bcorso** [comment]
Sorry, that was me! Thanks for letting me know (I had to run part of our release script manually and must have forgot to release that one).

I just released it, so should be available in ~10-15 minutes.

**Comment by unveloper** [comment]
Hi!

> It seems that Hilt `2.28.2` does not compatible with `androidx.hilt`. Maybe caused by newly introduced `SingletonComponent`?
> 
> ```
> error: [Hilt]
>   dagger.hilt.android.components.ApplicationComponent is not a valid Component. Did you add or remove code in package hilt_aggregated_deps? [dagger.hilt.android.components.ApplicationComponent]: java.lang.IllegalStateException: dagger.hilt.android.components.ApplicationComponent is not a valid Component. Did you add or remove code in package hilt_aggregated_deps? [dagger.hilt.android.components.ApplicationComponent]
>   	at com.google.common.base.Preconditions.checkState(Preconditions.java:843)
>   	at dagger.hilt.processor.internal.aggregateddeps.ComponentDependencies.from(ComponentDependencies.java:197)
>   	at dagger.hilt.processor.internal.root.RootProcessor.postRoundProcess(RootProcessor.java:139)
>   	at dagger.hilt.processor.internal.BaseProcessor.process(BaseProcessor.java:190)
> ```

I'm using 2.28.3-alpha of Gragle Plugin but I'm still having the error above.
I've created a module like this

```kotlin
package com.yyy.app.xxx.di

import com.yyy.app.xxx.domain.TestDependency
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.components.ApplicationComponent
import javax.inject.Singleton

@Module
@InstallIn(ApplicationComponent::class)
object TestModule {

	@Provides
	@Singleton
	fun provideTestDependency(): TestDependency {
		return TestDependency()
	}
}

```

What am I missing?
