### ISSUE TITLE
NPE due to superclass member injector created after subclass member injector

### ISSUE THREAD

**Issue by dalewking** [google/dagger#214]
So I have an abstract base class, BaseDialogFragment that does injection and then subclasses of that also do injection. I am seeing the component that is generated (in my case actually a subcomponent) such that it creates the MembersInjector for subclasses before it creates the MembersInjector for the base class. Because it needs the injector for the base class in order to create the injector for the subclass, it ends up passing a null for the superTypeInjector parameter and when you try to inject the subclass you get a null pointer exception.

There doesn't seem to be any dependency analysis done to determine what order the injectors need to be created in. The only way I have found to enforce the ordering is to explicitly define an inject method for the base class in the component and make sure that it comes BEFORE the subclass injection methods.

The code needs to analyze the dependencies to make sure they are created before being referenced.

**Comment by dalewking** [comment]
OK, I was incorrect, there doesn't seem to be a way to force it to create them in the correct order. In case it matters the only injection into BaseDialogFragment doesn't come from the actual subcomponent's modules but is provided by the parent component.

**Comment by svenjacobs** [comment]
What do you mean by "that does injection"? Do you explicitly call `component.inject(this)` in your base class? If so I made the experience that explicit injection in base classes should be avoided since the dependencies specified in the base class(es) are injected twice, once when the injection is performed in the base class and second when it's performed in the concrete class. Therefor in my Android projects I avoid calling the dependency injection explicitly in base classes.

If you look at my [Android example project](https://github.com/svenjacobs/dagger2-android-template) this case is exactly the reason why I've created the [onPostComponentCreated()](https://github.com/svenjacobs/dagger2-android-template/blob/master/android-template/src/main/java/com/svenjacobs/dagger/inject/ComponentLifecycle.java) lifecycle method. This method can be used by base classes to access and configure injected dependencies once the injection has been performed in the concrete class.

**Comment by dalewking** [comment]
It has nothing to do with when inject is called. The issue is in the actual class that Dagger generates. So I have my BaseDialogFragment that has something like:

    public abstract class BaseDialogFragment extends DialogFragment
    {
         @Inject Bus bus;

and I have 

    public class ForgotPasswordDialogFragment extends BaseDialogFragment
    {
        @Inject NetworkService networkService;

and with all lines unrelated to these 2 classes removed this is what Dagger generates:

    private final class ActivityComponentImpl implements ActivityComponent {
      private MembersInjector<ForgotPasswordDialogFragment> 
      private MembersInjector<BaseDialogFragment> baseDialogFragmentMembersInjector;

      private ActivityComponentImpl(ActivityModule activityModule) {  
        initialize();
        initialize1();
      }
    
      private void initialize() {  
       this.forgotPasswordDialogFragmentMembersInjector =
           ForgotPasswordDialogFragment_MembersInjector.create(
                 baseDialogFragmentMembersInjector,
                 DaggerAppComponent.this.provideNetworkServiceProvider,
                 DaggerAppComponent.this.provideEmailObservablePreferenceProvider);
     }
    
      private void initialize1() {  
        this.baseDialogFragmentMembersInjector =
            BaseDialogFragment_MembersInjector.create(
                 (MembersInjector) MembersInjectors.noOp(),
                 DaggerAppComponent.this.provideBusProvider);
      }
    }

Notice that in the `initialize()` method that `baseDialogFragmentMembersInjector` is passed to `ForgotPasswordDialogFragment_MembersInjector.create()`, __BUT__ it is still null at this point because it isn't initialized until later when `initialize1()` is called. So when you try to inject `ForgotPasswordDialogFragment` you get an NPE when it tries to use the null pointer it was given.

Luckily for our app the injection in the base class wasn't actually being used so I was able to rip it out and sidestep the problem, but this is a bug.

**Comment by svenjacobs** [comment]
That's interesting because I use base class injection and don't get any NPEs.
Do you get any warnings by Dagger when compiling?

**Comment by dalewking** [comment]
No warnings

**Comment by dalewking** [comment]
So I tried moving the inject method for the other class from the parent component to the sub component and it creates ti correctly. So the scenario that seems to cause a problem is to have a base class that needs injection and have one subclass injected in a component and another subclass injected in a sub component.

**Comment by prashanthsadasivan** [comment]
I know this issue is a little old, but I ran into this too. I've got an ApplicationComponent, an ActivityComponent (@Subcomponent of ApplicationComponent) and a FragmentComponent (@Subcomponent of ActivityComponent)

ApplicationComponent <- ActivityComponent <- FragmentComponent.

Here's the general gist of my component structure

```java

@Component(modules = ApplicationModule.class)
public interface ApplicationComponent {
    ActivityComponent plus(ActivityModule activity);
}

@Subcomponent(modules = ActivityModule.class)
public interface ActivityComponent {
    void inject(BaseActivity activity);

    void inject (Subclass1Act activity);
    void inject(Subclass2Act activity)

    FragmentComponent plus(FragmentModule module);
}

@Subcomponent(modules = FragmentModule.class)
public interface FragmentComponent {
    void inject(BaseFragment frag);

    void inject(Subclass1Frag frag);
    void inject(Subclass2Frag frag);
}

```

And my onCreate/onAttach method: 

```java
public class BaseActivity extends Activity {
    public void onCreate() {
        super.onCreate();
        getComponent().inject(this);
        inject(getComponent()); //to inject subclasses
    }
    
    //optional. subclasses can override if they have extra dependencies.
    public void inject(ActivityComponent component) {}
}

public class BaseFragment extends Fragment {

    public void onAttach(Activity act) {
        super.onAttach(act);
        BaseActivity act = (BaseActivity) act;
        FragmentComponent component = act.getComponent().plus(new FragmentModule(this));
        component.inject(this);
        inject(component); //to inject subclasses
    }
    //optional. subclasses can override if they have extra dependencies.
    public void inject(FragmentComponent component) {}
}
```

The generated code then comes to look like this:

```java
public class DaggerApplicationComponent {
    Subclass1FragmentMembersInjector subclass1fragmentinjector;
    BaseFragmentMembersInjector baseFragmentMembersInjector;
    // other stuff

    private void initialize() {
        //baseFragmentInjector is not yet initialized which causes the NPE!!!
        this.subclass1fragmentinjector = Subclass1FragmentMembersInjector.create(baseFragmentMembersInjector); 
        //other initializers...
        //now it's initialized after the subclass.
        this.baseFragmentMembersInjector = BaseFragmentMembersInjector(MembersInjector.noOp());

    }

}
```

I managed to fix it by enforcing all subclasses to inject themselves, and getting rid of the initial inject by the base class (since the subclass injector will inject the supertype dependencies). 

But I'm still curious why that causes the generated code to come out with a null pointer. It should either throw a compiler error if multiple injects to the same class are not supported, or it should simply generate the code in the correct order.

**Comment by jtietema** [comment]
I just run into this issue as well. My components look more like this. Where both activities extend the same base activity.

```java
@Component(modules = ApplicationModule.class)
public interface ApplicationComponent {
    void inject (Subclass1Act activity);
    ActivityComponent plus(ActivityModule activity);
}

@Subcomponent(modules = ActivityModule.class)
public interface ActivityComponent {
    void inject(Subclass2Act activity)
}
```

Making either activity not extend the base activity fixes the problem for me. I am not injecting into the base activity directly in my components.

**Comment by Piasy** [comment]
I came with this problem too, after I remove the `inject(BaseActivity)` method declaration in ApplicationComponent, the NPE goes away. 
B.T.W, the dependency in BaseActivity was injected correctly because when subclass activity called inject method, dependency in BaseActivity was injected properly too.

**Comment by spierce7** [comment]
I'm encountering this as well. I had made a separate issue, but someone pointed out it was a dupe of this. Here is my previous issue post:

In one of the `*_MembersInjector` class I'm seeing a NPE crash in the `injectMembers()` method, on the line: `supertypeInjector.injectMembers(instance);`.

After reviewing the generated code, I've been able to determine that supertypeInjector is null due to a bug in the initialization logic. The initialization logic has 6 steps for this component:

```Java
    private ActivityComponentImpl(ActivityModule activityModule) {  
      if (activityModule == null) {
        throw new NullPointerException();
      }
      this.activityModule = activityModule;
      initialize();
      initialize1();
      initialize2();
      initialize3();
      initialize4();
      initialize5();
    }
```

in the `initialize()` method, the `baseActivityMembersInjector` is being passed in to the creation of the `MainActivity_MembersInjector.create()` as the `supertypeInjector`. At the point that it's being passed in though, it's null. The `baseActivityMembersInjector` is not actually being initialized until `initialize4()`.

I've tinkered with it a bit, and I've been able to identify where the compiler is getting confused. I'll describe the system to you:

I have 2 components:
```Java
@Singleton
@Component
public interface ApplicationComponent {
    ActivityComponent plus(ActivityModule activityModule);
    void inject(Activity2 obj);
}
```

```Java
@Singleton
@Subcomponent
public interface ActivityComponent {
    void inject(MainActivity obj);
}
```

I have 2 Activities: `MainActivity`, and `Activity2`. Both of these activities extend `BaseActivity`. `BaseActivity`'s MembersInjector creation time is the issue. When I move `void inject(Activity2 obj);` from the `ApplicationComponent` to the `ActivityComponent`, everything works out fine and the crash doesn't happen.

This is not a complete representation of the dagger setup in my project. My dependency graph is far larger, but this should isolate the issue so that it's reproducible.

**Comment by tonyshkurenko** [comment]
Any nice solution? Seems like every solution here isn't common for this problem and was made as pretty painful decision to the architecture.

**Comment by jtietema** [comment]
Switching to component dependencies, instead of subcomponents, fixed our problems.

http://google.github.io/dagger/api/2.0/dagger/Component.html#component-dependencies

**Comment by netdpb** [comment]
The way MembersInjectors are initialized has changed, and this bug is fixed internally, but the snapshot has not yet been synced.

We're working on a sync this week.

**Comment by vytautasgimbutas** [comment]
Having the same issue. Any news on this? It's been a couple of weeks already.

**Comment by netdpb** [comment]
We pushed a snapshot last week. This issue should have been fixed by commit 49b4cd58fc0a4fc118095082d22a7fa72385fbc5 among others.

**Comment by ar-g** [comment]
The issue still remains when injecting parentclass in components with different scopes and using subcomponents like
```
@PerActivity @Subcomponent public interface ActivityScopeComponent {
  void inject(Child1 child1);
}
```
```
@Singleton @Component public interface AppTestComponent {
  ActivityScopeComponent plus();

  void inject(Child2 userHolder);
}
```
then it produce code like in this [gist](https://gist.github.com/ar-g/41f18a951ca216b4a57c#file-dagger2_code_generation_issue_daggerapptestcomponent-java-L64)

I created gist with full [example](https://gist.github.com/ar-g/9319c1da7c768538aa6b)

Before I exposed dependencies from other scopes. But now it's too much of them and subcomponents seems the only right solution.
